# Generated by Django 6.0.5 on 2026-05-13 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('category', models.CharField(choices=[('disease', 'Disease'), ('weather', 'Weather'), ('market', 'Market'), ('general', 'General')], default='general', max_length=10)),
                ('district', models.CharField(blank=True, help_text='Blank = nationwide', max_length=50)),
                ('source', models.CharField(default='Kilimo Hub', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('district', models.CharField(choices=[('kampala', 'Kampala'), ('mukono', 'Mukono'), ('wakiso', 'Wakiso'), ('jinja', 'Jinja'), ('gulu', 'Gulu'), ('mbarara', 'Mbarara'), ('arua', 'Arua'), ('lira', 'Lira'), ('soroti', 'Soroti')], default='mukono', max_length=50)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('ach', 'Acholi'), ('ny', 'Runyankore')], default='en', max_length=5)),
                ('farm_size_acres', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
