# Generated by Django 6.0.5 on 2026-05-13 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('local_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(default='crop', max_length=50)),
                ('unit', models.CharField(choices=[('kg', 'per kg'), ('bag', 'per bag (100kg)'), ('bunch', 'per bunch'), ('head', 'per head')], default='kg', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ugx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.CharField(default='Kilimo Hub Agent', max_length=100)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.commodity')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.market')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'get_latest_by': 'recorded_at',
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alert_above', models.BooleanField(default=True, help_text='Alert when price goes above target')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.commodity')),
            ],
        ),
    ]
