# Generated by Django 6.0.5 on 2026-05-13 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('crop_affected', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('treatment', models.TextField()),
                ('prevention', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='diseases/')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='disease_reports/')),
                ('description', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('crop_name', models.CharField(blank=True, max_length=100)),
                ('ai_diagnosis', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('identified', 'Identified'), ('confirmed', 'Confirmed')], default='pending', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reporter_phone', models.CharField(blank=True, max_length=15)),
                ('identified_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disease.disease')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
