# Generated by Django 6.0.5 on 2026-05-13 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('local_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VetChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('messages_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('disease_prevented', models.CharField(max_length=200)),
                ('first_dose_age', models.CharField(max_length=100)),
                ('booster_interval', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.animal')),
            ],
        ),
        migrations.CreateModel(
            name='VetCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symptoms', models.TextField()),
                ('treatment', models.TextField()),
                ('prevention', models.TextField(blank=True)),
                ('is_notifiable', models.BooleanField(default=False, help_text='Must be reported to MAAIF')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.animal')),
            ],
        ),
    ]
